export const categories = [
  {
    name: "Lawn",
    slug: "lawn",
    image: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=600&h=700&fit=crop",
    count: 48,
  },
  {
    name: "Cotton",
    slug: "cotton",
    image: "https://images.unsplash.com/photo-1606722590583-6951b5ea92ad?w=600&h=700&fit=crop",
    count: 36,
  },
  {
    name: "Silk",
    slug: "silk",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=700&fit=crop",
    count: 24,
  },
  {
    name: "Khaddar",
    slug: "khaddar",
    image: "https://images.unsplash.com/photo-1620799139507-2a76f79a2f4d?w=600&h=700&fit=crop",
    count: 30,
  },
]

export const products = [
  {
    id: 1,
    name: "Emerald Dream Lawn Suit",
    price: 4500,
    originalPrice: 5500,
    category: "Lawn",
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=500&h=600&fit=crop",
    badge: "Sale",
    rating: 4.5,
    reviews: 28,
    inStock: true,
    description: "A beautifully crafted lawn suit featuring intricate embroidery with a modern design. Perfect for summer occasions.",
    fabric: "Premium Lawn",
    pieces: "3 Piece (Shirt, Trouser, Dupatta)",
    weight: "1.2 kg",
  },
  {
    id: 2,
    name: "Royal Maroon Cotton",
    price: 3800,
    originalPrice: null,
    category: "Cotton",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=600&fit=crop",
    badge: null,
    rating: 4.8,
    reviews: 42,
    inStock: true,
    description: "Elegant cotton fabric with a royal maroon palette. Comfortable for daily and semi-formal wear.",
    fabric: "Pure Cotton",
    pieces: "Unstitched (3.5 meters)",
    weight: "0.8 kg",
  },
  {
    id: 3,
    name: "Pearl White Silk Dupatta",
    price: 6200,
    originalPrice: 7500,
    category: "Silk",
    image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=500&h=600&fit=crop",
    badge: "New",
    rating: 4.9,
    reviews: 15,
    inStock: true,
    description: "Luxurious pearl white silk dupatta with delicate borders. An essential accessory for formal events.",
    fabric: "Pure Silk",
    pieces: "1 Piece (Dupatta)",
    weight: "0.3 kg",
  },
  {
    id: 4,
    name: "Classic Khaddar Collection",
    price: 3200,
    originalPrice: null,
    category: "Khaddar",
    image: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=500&h=600&fit=crop",
    badge: null,
    rating: 4.3,
    reviews: 37,
    inStock: true,
    description: "Traditional khaddar fabric with a classic weave pattern. Ideal for winter comfort and style.",
    fabric: "Khaddar",
    pieces: "Unstitched (4 meters)",
    weight: "1.0 kg",
  },
  {
    id: 5,
    name: "Blush Pink Organza",
    price: 8500,
    originalPrice: 9500,
    category: "Silk",
    image: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d44?w=500&h=600&fit=crop",
    badge: "Sale",
    rating: 4.7,
    reviews: 21,
    inStock: true,
    description: "Stunning blush pink organza with sequin work. Perfect for weddings and festive celebrations.",
    fabric: "Organza Silk",
    pieces: "3 Piece (Shirt, Trouser, Dupatta)",
    weight: "1.1 kg",
  },
  {
    id: 6,
    name: "Ocean Blue Lawn Print",
    price: 4200,
    originalPrice: null,
    category: "Lawn",
    image: "https://images.unsplash.com/photo-1622398925373-3f91b1e275f5?w=500&h=600&fit=crop",
    badge: "New",
    rating: 4.4,
    reviews: 19,
    inStock: true,
    description: "Vibrant ocean blue lawn print with digital motifs. A refreshing summer collection piece.",
    fabric: "Digital Print Lawn",
    pieces: "3 Piece (Shirt, Trouser, Dupatta)",
    weight: "1.2 kg",
  },
  {
    id: 7,
    name: "Golden Thread Cotton",
    price: 5100,
    originalPrice: 6000,
    category: "Cotton",
    image: "https://images.unsplash.com/photo-1558171814-5e3c96cfad5d?w=500&h=600&fit=crop",
    badge: "Sale",
    rating: 4.6,
    reviews: 33,
    inStock: false,
    description: "Premium cotton with golden thread embroidery. Sophisticated design for special occasions.",
    fabric: "Embroidered Cotton",
    pieces: "Unstitched (3.5 meters)",
    weight: "0.9 kg",
  },
  {
    id: 8,
    name: "Midnight Velvet Shawl",
    price: 7800,
    originalPrice: null,
    category: "Khaddar",
    image: "https://images.unsplash.com/photo-1614676471928-2ed0ad1061a4?w=500&h=600&fit=crop",
    badge: "New",
    rating: 4.8,
    reviews: 11,
    inStock: true,
    description: "Rich midnight velvet shawl with traditional Kashmiri embroidery. A winter wardrobe essential.",
    fabric: "Velvet",
    pieces: "1 Piece (Shawl)",
    weight: "0.6 kg",
  },
]

export const newArrivals = products.filter(p => p.badge === "New")

export const cartItems = [
  { ...products[0], quantity: 2 },
  { ...products[2], quantity: 1 },
  { ...products[4], quantity: 1 },
]

export const orders = [
  { id: "ORD-001", date: "2026-02-15", status: "Delivered", total: 13200, items: 3 },
  { id: "ORD-002", date: "2026-02-20", status: "Processing", total: 8500, items: 2 },
  { id: "ORD-003", date: "2026-02-25", status: "Shipped", total: 4200, items: 1 },
]

export const adminStats = {
  totalUsers: 1248,
  totalOrders: 856,
  totalRevenue: 2450000,
  totalProducts: 142,
}

export const recentOrders = [
  { id: "ORD-101", customer: "Aisha Khan", date: "2026-02-28", status: "Pending", total: 9500 },
  { id: "ORD-102", customer: "Sara Ahmed", date: "2026-02-27", status: "Processing", total: 4200 },
  { id: "ORD-103", customer: "Fatima Ali", date: "2026-02-26", status: "Shipped", total: 12800 },
  { id: "ORD-104", customer: "Zainab Malik", date: "2026-02-25", status: "Delivered", total: 6500 },
  { id: "ORD-105", customer: "Hina Raza", date: "2026-02-24", status: "Delivered", total: 15200 },
]

export function formatPrice(price: number): string {
  return `Rs. ${price.toLocaleString()}`
}
